### ISSUE TITLE
add __weakref__ slot support

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/tokio#13]
what classes should support weakrefs? PyHandle, PyTimerHandler needs to support for sure. what about Future and Task objects?

**Comment by 1st1** [comment]
Basically all asyncio objects that users can interact with: transports, `Future` and `Task`.

**Comment by fafhrd91** [comment]
I am not sure how implement this, rust doesn't provide `offset_of`, we may use some macro, but I do not know rust enough

**Comment by fafhrd91** [comment]
fixed

**Comment by fafhrd91** [comment]
interesting. weakref costs 30% of performance 

@1st1 is this expected?

**Comment by 1st1** [comment]
No, it's not. Perhaps the regression is in something else.

**Comment by fafhrd91** [comment]
ok

**Comment by fafhrd91** [comment]
Everything seems working as expected. My benchmarks was wrong
