### ISSUE TITLE
add PyBytes.split method

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/tokio#18]
https://docs.python.org/3/library/stdtypes.html#bytes.split

**Comment by fafhrd91** [comment]
async-tokio depends on `twoway` create. `twoway::find_bytes` could be used for substring search

**Comment by messense** [comment]
I wonder is the signature is right:

```rust
def split(&self, sep: Option<cpython::PyBytes>, maxsplit: Option<usize> = None) -> PyResult<Vec<cpython::PyBytes>> {
    unimplemented!();
}
```

**Comment by messense** [comment]
`test_pybytes` seems hang when I am running `cargo test` on macOS 10.12.4 with CPython 3.6.1

**Comment by fafhrd91** [comment]
test works for me. I use `cargo test --features=cpython/python3-sys`.

I think split method should be like this:

```rust
def split(&self, sep: Option<cpython::PyBytes> = None, maxsplit: Option<isize> = None) -> PyResult<PyList> {
    unimplemented!();
}
```

`sep` could be None. PyList is just optimization, Vec<> would be explicitly converted to list in wrapper code.

**Comment by fafhrd91** [comment]
there is glitter channel for realtime communications, quite empty yet.

https://gitter.im/PyO3/Lobby

**Comment by fafhrd91** [comment]
fixed
