### ISSUE TITLE
Transport.get_extra_info('socket') should return a socket-like object

### ISSUE THREAD

**Issue by 1st1** [PyO3/tokio#2]
While working on `uvloop` I've iterated on the following three different approaches to how `get_extra_info('socket')` should be implemented:

1. Wrap the underlying socket FD into a Python socket object: `socket.socket(fileno=FD)`. The downside of this approach is that Python will try to control the FD. For instance, when the socket object is GCed, Python will try to close the FD, which isn't acceptable for uvloop and asyncio-tokio. Moreover, beginning with Python 3.6 there is a race to who closes the socket first, and Python expects to win, otherwise it will raise an `IOError` in `socket.close()`.

2. Duplicate the FD before wrapping (currently implemented in uvloop). This fixes (1), but has its own downsides: FDs are a limited resource and now we need 2x of them; FDs can stay alive longer than necessary (if the transport is closed, but its duplicated sockets are alive).

3. Return a socket-like object. Essentially, the object should implement all `socket.socket` methods and have all of its attributes (to be duck-type compatible), but the implementation of `socket.close()` and `socket.shutdown()` will be empty (or will raise an error).

The third option is the one I want to implement in uvloop, and I believe the one we need to implement for asyncio-tokio.

**Comment by fafhrd91** [comment]
option 3 should relatively easy to implement. good task to get up to speed with rust and rust-cpython

**Comment by fafhrd91** [comment]
we need same socket-like objects for `Server.sockets`

**Comment by 1st1** [comment]
I'll try to work on this. If you get to it first don't wait for me :)

**Comment by fafhrd91** [comment]
added, ssl info is still missing though
