### ISSUE TITLE
do we need python3.5 support?

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/tokio#37]

**Comment by 1st1** [comment]
Do you want to use some 3.6 exclusive features?

**Comment by fafhrd91** [comment]
not really, but need to do some fixes in rust-cpython

**Comment by 1st1** [comment]
I'd say it's OK to drop 3.5 support. People who use 3.5 and want to use experimental event loop written in Rust generally should be flexible enough to start using 3.6.

**Comment by fafhrd91** [comment]
Ok, then let's do 3.6 for right now
