### ISSUE TITLE
documentation error: TokioLoopPolicy not EventLoopPolicy

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/tokio#41]
I just had a quick try with tokio, I'm currently getting a slightly speed up (~5%) compared to asyncio loop, but significantly less quick than uvloop. Is that to be expected at this stage?

Also your readme refer to `tokio.EventLoopPolicy()` which is wrong, as of pypi v0.1.0 the policy is called `tokio.TokioLoopPolicy()`

**Comment by fafhrd91** [comment]
Did you build it with release settin?

**Comment by samuelcolvin** [comment]
i just installed from pypi

**Comment by fafhrd91** [comment]
Pypi version is too old. Master branch is unstable at the moment. I am replacing rust-cpython binding with pyo3. Should be ready in several days

**Comment by fafhrd91** [comment]
From my measurements, tokio is slower 5-10% than uvloop at the moment.

**Comment by samuelcolvin** [comment]
ok, thanks. Looking forward to it.

**Comment by fafhrd91** [comment]
In any case performance is import but not main reason for this project

**Comment by iAnanich** [comment]
@fafhrd91And what is the main reason?

**Comment by fafhrd91** [comment]
Main reason is integration with rust and tokio-rs, so if you need performance you can gradually migrate from python to rust.

 It is very hard to make something as fast as libuv and uvloop. It is possible to speed up tokio in python case but only by introducing unsafe code.
Also I started to work on rust web framework, and it seems writing rust is simple enough, so at this point I do not see much reasons for asyncio tokio to exist, except educational purpose

**Comment by fafhrd91** [comment]
@iAnanich you are welcome to join and fix performance! :) I have some ideas, just don’t have enough time

**Comment by samuelcolvin** [comment]
> Main reason is integration with rust and tokio-rs, so if you need performance you can gradually migrate from python to rust.

Would be great to have an example of how to gradually migrate, eg. how build a performance critical views with rust? I've had a look but couldn't find such an example, maybe I'm being dumb?

**Comment by fafhrd91** [comment]
I'd start with simple extension. it is easier to build some function without any io in it. 
but migration depends on project there is no single example how to so this.

**Comment by iAnanich** [comment]
@fafhrd91 Actually I'm here only because of this [post](https://blog.sentry.io/2017/11/14/evolving-our-rust-with-milksnake) on Sentry's blog. It is about `milksnake` library that can be used to connect rust and python.
But I'm looking for a way to serve 10,000 post requests in 10 minutes (to gather answers from a poll) too.

I don't want to develop something in an improper way (You said that project is not about performance and I'm not sure that I have enough experience and skill), and not to today ;)

**Comment by fafhrd91** [comment]
for 10k posts request in 10 minutes you don't really need rust, python would work perfectly well. 
"is not about performance" means it is not about 100k sec business logic requests

**Comment by samuelcolvin** [comment]
Off topic but you can (fairly) easily do 1000requests/minute with python, aiohttp and uvloop. Your only risk is database load and associated latency, you might want to put the results into a redis list and process them on a worker.
