### ISSUE TITLE
Port uvloop unittests or move them into a separate package

### ISSUE THREAD

**Issue by 1st1** [PyO3/tokio#5]
As opposed to asyncio, which relies on mock tests a lot, uvloop contains a good number of functional unittests. They cross-test uvloop and asyncio to ensure full compatibility.

**Comment by fafhrd91** [comment]
I played with unit tests. most of test_futures tests pass, except repr, and remove callback.

**Comment by fafhrd91** [comment]
most of test_tasks pass. except `test_task_step_with_baseexception` which uses direct call to `_step`

also `test_task_current_task` does not pass, but that is because of `asyncio.Task.current_task` api
