### ISSUE TITLE
tokio object can not set python attr

### ISSUE THREAD

**Issue by LuoZijun** [PyO3/tokio#53]
https://github.com/PyO3/tokio/blob/master/tokio/__init__.py#L9

```python
import asyncio
import tokio

asyncio.set_event_loop_policy(tokio.EventLoopPolicy())

loop = tokio.new_event_loop()
asyncio.set_event_loop(loop)

class Empty(object):
    pass

# This not work!
loop.xyz = Empty()

```

**Comment by fafhrd91** [comment]
This is known limitation of pyo3. Next vetsion will support `__dict__` and AbstractEventLook

**Comment by messense** [comment]
@LuoZijun The limitation of pyo3 has been addressed in https://github.com/PyO3/pyo3/pull/68 FYI

**Comment by LuoZijun** [comment]
@messense @fafhrd91 okay.

**Comment by fafhrd91** [comment]
should be fixed in master
