### ISSUE TITLE
impl future::Future for PyFuture

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/tokio#6]
what type `PyFuture` should resolve to?

currently, `Future::Item` is `PyResult<PyObject>` and `Future::Err` is `unsync::oneshot::Cancelled`

future handling code looks like:
```rust

PyFuture::new(...).map(|res: PyResult<PyObject>| {
    match res {
        Ok(obj) => "do something with result (PyObject)"
        Err(err) => "do something with py exception"
    }
}).map_err(|err| "cancelled");
```

other option is to use `PyObject` as `Future::Item` and `PyErr` as `Future::Err`:
```rust

PyFuture::new(...).map(|res: PyObject| {
    "do something with result (PyObject)"
}).map_err(|err| {
    "do something with py exception"
);
```

I like second option, but there would be no explicit cancelation state

**Comment by 1st1** [comment]
> I like second option, but there would be no explicit cancelation state

Precisely knowing that you are handling cancellation can be very helpful sometimes. It looks like it's easier to handle cancellation with the first approach (and it also looks more idiomatic, no?)

**Comment by fafhrd91** [comment]
I think main question how we treat python exception. If it is error state of future then we should use second approach otherwise first is fine. we need Future trait only if we want to wait async result from python in rust code, so what would be more ergonomic?

`map_err` is mapping function same as `map` just for `Err`.

**Comment by 1st1** [comment]
> If it is error state of future then we should use second approach otherwise first is fine.

Right. In Python both error state of the `Future` (say `InvalidStateError` or `CancelledError`) and exceptions set to it aren't well separated (`Future.result()` can raise both). I think you're right, second approach should work just fine.

**Comment by fafhrd91** [comment]
Note on `map_err`, Tokio can run only `Future<Item=(), Error=()>` futures, so some code needs to map `Future<Item=PyObject, Error=PyErr>` future to tokio core compatible future, whether it consumer of the future or framework

**Comment by fafhrd91** [comment]
I am actually wrong. Tokio support any future, but TokioEventLoop controls what future it uses for tokio core

**Comment by fafhrd91** [comment]
closing this issue.

stick with:
```rust
Future<Item=PyResult<PyObject>, Error=unsync::oneshot::Canceled>
```
