### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by itdaniher** [PyO3/tokio#77]
```
(tokio) rocklobster:~/python/tokio $ python setup.py build
running build
running build_py
running egg_info
writing tokio.egg-info/PKG-INFO
writing dependency_links to tokio.egg-info/dependency_links.txt
error[E0308]: mismatched typesio.egg-info/top_level.txt
  --> /home/name/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/68937db/src/objects/string.rs:54:21
   |> /home/name/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/68937db/src/objects/string.rs:53:21
   = note: expected type `*const u8`tr() as *const i8)) pyo3/python3 pyo3/extension-module --release -- --crate-type cderror: aborting due to 2 previous errors^^^^^^^^^^^^^ expected u8, found i8
error: cargo failed with code: 101^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
To learn more, run the command again with --verbose.
```

Python 3.6.3
rustc 1.23.0-nightly (827cb0d61 2017-11-26)
aarch64

looks like a solvable issue, just haven't hit the source yet.

**Comment by fafhrd91** [comment]
works for me. could you run "cargo update" and try to build again

**Comment by fafhrd91** [comment]
btw what is the reason for you to try pyo3 tokio?

**Comment by fafhrd91** [comment]
I just updated lock file, you can pull latest change and try to build again

**Comment by itdaniher** [comment]
> btw what is the reason for you to try pyo3 tokio?

I have a network-oriented application built in Python3 with asyncio and uvloop that is occasionally CPU-bound. I've identified the "slow" portions of my software and I'm trying to move them to a tight loop in Rust. Tokio seems like a useful tool / educational project to explore along the way.

**Comment by fafhrd91** [comment]
ok, makes sense. But you should not use pyo3 tokio in production, I do not recommend :)
and as a python event loop, uvloop is faster.

**Comment by fafhrd91** [comment]
should be fixed in master

**Comment by itdaniher** [comment]
it's not, but it needs a patch to PyO3 to work on my system.
